---
title: 'ActivitySim Mode Distribution'
author: "Hayden Atchley"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load_packages, include=FALSE}
library(tidyverse)
library(knitr)
```

```{r load_data}
plans <- read_csv("data/wfrc/plans.csv") %>% 
  select(personId, legMode, planElementType, activityType, primaryPurpose) %>% 
  mutate(activityType = if_else(is.na(activityType), lead(activityType), activityType)) %>% 
  filter(planElementType == "leg") %>% 
  select(-planElementType)
```

## Overall mode split

```{r overall}
plans %>% 
  count(legMode) %>% 
  ggplot(aes(x = legMode, y = n)) +
  geom_col(aes(fill=legMode)) +
  theme_minimal() +
  labs(x = "Mode",
       y = "Number of Legs Traveled") +
  theme(legend.position = "NONE",
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1.1, hjust = 1.1))
```

## \ 

```{r}
plans %>% 
  count(legMode) %>% 
  ggplot(aes(x = 1, y = n)) +
  geom_col(aes(fill=legMode), position = "fill") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(fill = "Mode",
       x = NULL,
       y = "Mode Split")
```


## By purpose

```{r}
table(plans$primaryPurpose, plans$legMode) %>% 
  kable()
```

## \ 

```{r}
plans %>% 
  count(legMode, primaryPurpose) %>% 
  ggplot(aes(x=primaryPurpose, y=n, fill=legMode)) +
  geom_col(position = "fill") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank()) +
  labs(x = "Tour Purpose",
       y = "Mode Split",
       fill = "Mode")
```

